#!/usr/bin/env python3
"""
Generate embedded_waveguide_kernels.h with complete Metal kernel source.
This eliminates runtime file loading issues when code is in an app bundle.
"""

import sys
from pathlib import Path

def read_file(path: Path) -> str:
    """Read file content as string."""
    try:
        return path.read_text(encoding='utf-8')
    except Exception as e:
        print(f"Error reading {path}: {e}", file=sys.stderr)
        sys.exit(1)

def main():
    # Paths relative to script location
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent.parent
    
    # Input files
    layout_structs_path = repo_root / 'src' / 'waveguide' / 'include' / 'waveguide' / 'metal' / 'layout_structs.metal'
    common_path = repo_root / 'src' / 'waveguide' / 'include' / 'waveguide' / 'metal' / 'common.metal'
    kernels_path = repo_root / 'src' / 'metal' / 'src' / 'waveguide_kernels.metal'
    
    # Output file
    output_path = repo_root / 'src' / 'metal' / 'src' / 'embedded_waveguide_kernels.h'
    
    # Verify input files exist
    for path in [layout_structs_path, common_path, kernels_path]:
        if not path.exists():
            print(f"Error: Required file not found: {path}", file=sys.stderr)
            sys.exit(1)
    
    # Read input files
    layout_structs = read_file(layout_structs_path)
    common = read_file(common_path)
    kernels = read_file(kernels_path)
    
    # Strip the #include from common.metal
    common_lines = common.split('\n')
    common_without_includes = []
    for line in common_lines:
        if '#include "waveguide/metal/layout_structs.metal"' in line:
            continue
        common_without_includes.append(line)
    common_clean = '\n'.join(common_without_includes)
    
    # Strip the #include from waveguide_kernels.metal
    kernels_lines = kernels.split('\n')
    kernels_without_includes = []
    for line in kernels_lines:
        if '#include "waveguide/metal/layout_structs.metal"' in line:
            continue
        kernels_without_includes.append(line)
    kernels_clean = '\n'.join(kernels_without_includes)
    
    # Combine in correct order
    complete_source = f"""{layout_structs}

// ============================================================================
// Common helper functions (from waveguide/metal/common.metal)
// ============================================================================

{common_clean}

// ============================================================================
// Main waveguide kernels (from waveguide_kernels.metal)
// ============================================================================

{kernels_clean}
"""
    
    # Generate header file with R"( )" raw string literal
    header_content = f"""// Auto-generated by embed_metal_kernels.py
// DO NOT EDIT THIS FILE MANUALLY

#pragma once

namespace wayverb {{
namespace metal {{

inline const char* get_embedded_waveguide_kernels() {{
    return R"METAL_SOURCE(
#include <metal_stdlib>
using namespace metal;

{complete_source}
)METAL_SOURCE";
}}

}}  // namespace metal
}}  // namespace wayverb
"""
    
    # Write output file
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(header_content, encoding='utf-8')
        print(f"Successfully generated: {output_path}")
        return 0
    except Exception as e:
        print(f"Error writing {output_path}: {e}", file=sys.stderr)
        return 1

if __name__ == '__main__':
    sys.exit(main())
